version: '3.7'
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
  db:
      image: mariadb:10.8.2
      restart: always
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql
      environment:
        - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
        - MARIADB_DATABASE=${DATABASE_NAME}

volumes:
  db:
